2019-03-30 08:40:59,110 INFO: TempestBlog startup [in C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\__init__.py:43]
2019-03-30 09:07:03,239 INFO: TempestBlog startup [in C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\__init__.py:43]
2019-03-30 09:07:13,744 INFO: TempestBlog startup [in C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\__init__.py:43]
2019-03-30 16:07:53,408 INFO: TempestBlog startup [in C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\__init__.py:43]
2019-03-30 18:13:56,123 INFO: TempestBlog startup [in C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\__init__.py:43]
2019-03-30 19:21:10,219 INFO: TempestBlog startup [in C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\__init__.py:45]
2019-03-30 19:21:16,319 ERROR: Exception on /login [GET] [in c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\routes.py", line 58, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\templates\login.html", line 23, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\werkzeug\routing.py", line 2182, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2019-03-30 19:21:18,947 ERROR: Exception on /login [GET] [in c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\routes.py", line 58, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\templates\base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\Nicho\Desktop\PythonProjects\TempestDragon\app\templates\login.html", line 23, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\nicho\desktop\pythonprojects\tempestdragon\venv\lib\site-packages\werkzeug\routing.py", line 2182, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
